name: Deploy Simple API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-api:latest .

    - name: Push da imagem para o Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-api:latest

    - name: Deploy na EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop simple-api-container || true
          docker rm simple-api-container || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-api:latest
          docker run -d -p 3000:3000 --name simple-api-container ${{ secrets.DOCKER_USERNAME }}/simple-api:latest

